language: C
dist: focal
sudo: true

env:
  - RELEASE_VERSION=$(wget -q "https://ftp.gnu.org/pub/gnu/emacs/?C=M;O=D" -O - | grep -oe ">emacs-.*tar.gz" | head -n 1 | cut -d - -f 2 | sed -e 's|.tar.gz||g')
  - CC="gcc-10"
  
script:
  - wget -c "http://git.savannah.gnu.org/cgit/emacs.git/snapshot/emacs-master.tar.gz"
  - tar xf emacs-master.tar.gz
  - rm emacs-master.tar.gz
  - cd emacs*
  - git checkout feature/native-comp
  - sudo apt-get build-dep emacs
  - sudo apt-get -y install libgtk-3-dev libwebkitgtk-3.0-dev libjansson-dev
  - add-apt-repository ppa:ubuntu-toolchain-r/ppa && apt-get update -y && apt-get install -y gcc-10 libgccjit0 libgccjit-10-dev
  - ./autogen.sh
  - ./configure --prefix=/app --without-selinux --with-x-toolkit=gtk3 --with-modules --with-nativecomp
  - make -j$(nproc)
  - sudo make install
  - cd ..
  - sudo apt-get -y install squashfs-tools
  - bash -ex appimage.sh || echo success
  
after_success:
  - readlink -f .
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ../../../out/*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
