language: C
dist: focal
sudo: true
  
script:
  - git clone https://git.savannah.gnu.org/git/emacs.git
  - cd emacs*
  - git checkout feature/native-comp
  - sudo apt-get build-dep emacs
  - sudo apt-get -y install libgtk-3-dev libwebkitgtk-3.0-dev libjansson-dev
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa && sudo apt-get update -y && sudo apt-get install -y gcc-10 libgccjit0 libgccjit-10-dev
  - ./autogen.sh
  - ./configure --prefix=/app --without-selinux --with-x-toolkit=gtk3 --with-modules --with-nativecomp
  - CC="gcc-10" make -j$(nproc)
  - sudo make install
  - cd ..
  - sudo apt-get -y install squashfs-tools
  - bash -ex appimage.sh
  
after_success:
  - readlink -f .
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ../../../out/*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
