language: C
dist: focal
sudo: true

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # packages for building emacs
            - libgtk-3-dev
            - libwebkit2gtk-4.0-dev
            # C json parse
            - libjansson-dev
            # packages for gccemacs
            - gcc-10
            - libgccjit0
            - libgccjit-10-dev
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
  - eval "${MATRIX_EVAL}"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - set -e
  - git clone https://git.savannah.gnu.org/git/emacs.git
  - cd emacs*
  - git checkout feature/native-comp
  - sudo apt-get build-dep emacs
  - # check that libgccjit header can be found by gcc-10
  - dpkg --listfiles libgccjit-10-dev
  - echo -n | gcc-10 -xc -E -v -
  - ./autogen.sh
  - ./configure --prefix=/app --without-selinux --with-x-toolkit=gtk3 --with-modules --with-nativecomp || (cat config.log; exit -1)
  - make -j$(nproc) NATIVE_FULL_AOT=1
  - sudo make install
  - cd ..
  - sudo apt-get -y install squashfs-tools
  - bash -ex appimage.sh

after_success:
  - readlink -f .
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ../../../out/*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
