name: build-appimage
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup environment
        # gcc 10 available @ "Ubuntu > 16.xx": https://github.com/actions/virtual-environments/issues/1604#issuecomment-705498375
        run: |
          sudo apt update
          # common dependencies
          sudo apt-get install -qq -y libxpm-dev libjpeg-dev libgnutls28-dev libgif-dev libtiff-dev libacl1-dev libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev libmagickcore-dev libgpm-dev libselinux1-dev libm17n-dev libotf-dev libsystemd-dev
          # gcc-emacs + native JSON dependencies
          sudo apt-get install -qq -y libjansson-dev gcc-10 libgccjit0 libgccjit-10-dev


      - name: download
        run:
          git clone --depth 1 --single-branch --branch feature/native-comp https://git.savannah.gnu.org/git/emacs.git
      - name: configure
        env:
          CC: gcc-10
          CXX: g++-10
        working-directory: ./emacs
        run: |
          ./autogen.sh
          #                     ↓ target /usr according to AppImage docs
          ./configure --prefix=/usr --without-selinux --with-x-toolkit=gtk3 --with-modules --with-nativecomp || (cat config.log; exit -1)
      - name: prevent install from failing
        working-directory: ./emacs
        run: |
          # This step is not supposed to even exist, but I'm trying out if it helps with ↓ at "install" step
          # `/usr/bin/install -c -m 644 src/emacs.pdmp "AppDir/usr/libexec/emacs/28.0.50/x86_64-pc-linux-gnu"/emacs.pdmp`
          mkdir -p AppDir/usr/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/
      - name: build
        working-directory: ./emacs
        run: |
          make -j$(nproc) NATIVE_FULL_AOT=1
      - name: install build to dest directory
        working-directory: ./emacs
        run: |
          #              ↓ this matches DESTDIR above
          export DESTDIR=AppDir
          make install
      - name: Build AppImage
        working-directory: ./emacs
        run: |
          curl -Lo ./linuxdeploy-x86_64.AppImage \
          -z ./AppDir/linuxdeploy-x86_64.AppImage \
          https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x ./linuxdeploy-x86_64.AppImage

          # TODO: dunno if ↓ this is needed
          export OUTPUT=emacs.appimage

          ./linuxdeploy-x86_64.AppImage --appdir ./AppDir \
          -d ./etc/emacs.desktop \
          -i ./etc/images/icons/hicolor/128x128/apps/emacs.png \
          --output appimage
        #uses: AppImageCrafters/build-appimage-action@master
        #env:
        #  UPDATE_INFO: gh-releases-zsync|FelipeLema|Emacs.AppImage|latest|*x86_64.AppImage.zsync
        #with:
        #  recipe: AppImageBuilder.yml
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: AppImage
